version: "3.3"
services:
  db:
    container_name: coolmovies-db
    restart: unless-stopped
    image: coolmovies-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432

networks:
  network:

volumes:
  db: